/* The following code was generated by JFlex 1.4.3 on 11/17/25, 10:01 PM */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 11/17/25, 10:01 PM from the specification file
 * <tt>exemploGC.flex</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\20\1\2\2\0\1\3\22\0\1\20\1\31\1\57\1\0"+
    "\1\4\1\26\1\32\1\0\1\26\1\26\1\26\1\21\1\26\1\22"+
    "\1\26\1\26\12\1\1\25\1\26\1\30\1\23\1\27\1\24\1\0"+
    "\1\7\1\60\1\10\1\60\1\11\1\15\6\60\1\16\1\14\1\13"+
    "\2\60\1\6\1\17\1\5\6\60\1\26\1\0\1\26\1\0\1\12"+
    "\1\0\1\42\1\43\1\56\1\45\1\51\1\37\1\60\1\52\1\34"+
    "\1\60\1\55\1\40\1\46\1\35\1\41\2\60\1\50\1\53\1\36"+
    "\1\54\1\44\1\47\3\60\1\26\1\33\1\26\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\1\1\1\4\1\5\3\6"+
    "\1\7\1\10\4\6\2\1\14\4\1\1\2\0\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\4\1\22\7\4\1\23\7\4\3\0\1\24\2\4"+
    "\1\25\13\4\1\26\2\0\1\27\2\4\1\30\1\4"+
    "\1\31\1\32\2\4\1\33\1\34\2\4\2\0\1\35"+
    "\1\36\1\37\1\40\1\41\2\4\2\0\1\42\1\4"+
    "\2\0\1\4\2\0\1\43\1\44\2\0\1\45\1\46";

  private static int [] zzUnpackAction() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\61\0\223\0\304\0\365\0\u0126"+
    "\0\u0157\0\u0188\0\u01b9\0\61\0\61\0\61\0\u01ea\0\u021b"+
    "\0\u024c\0\u027d\0\u02ae\0\u02df\0\u0310\0\u0341\0\u0372\0\u03a3"+
    "\0\u03d4\0\u0405\0\u0436\0\u0467\0\u0498\0\u04c9\0\u04fa\0\u052b"+
    "\0\u055c\0\u058d\0\61\0\61\0\61\0\61\0\61\0\61"+
    "\0\61\0\61\0\61\0\u05be\0\365\0\u05ef\0\u0620\0\u0651"+
    "\0\u0682\0\u06b3\0\u06e4\0\u0715\0\365\0\u0746\0\u0777\0\u07a8"+
    "\0\u07d9\0\u080a\0\u083b\0\u086c\0\u089d\0\u08ce\0\u08ff\0\365"+
    "\0\u0930\0\u0961\0\365\0\u0992\0\u09c3\0\u09f4\0\u0a25\0\u0a56"+
    "\0\u0a87\0\u0ab8\0\u0ae9\0\u0b1a\0\u0b4b\0\u0b7c\0\u089d\0\u0bad"+
    "\0\u0bde\0\365\0\u0c0f\0\u0c40\0\365\0\u0c71\0\365\0\365"+
    "\0\u0ca2\0\u0cd3\0\365\0\365\0\u0d04\0\u0d35\0\u0d66\0\u0d97"+
    "\0\365\0\365\0\365\0\365\0\365\0\u0dc8\0\u0df9\0\u0e2a"+
    "\0\u0e5b\0\365\0\u0e8c\0\u0ebd\0\u0eee\0\u0f1f\0\u0f50\0\u0f81"+
    "\0\365\0\61\0\u0fb2\0\u0fe3\0\61\0\61";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\5\7\1\2\5\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\7\1\25\1\26"+
    "\3\7\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\7\1\36\2\7\1\37\1\40\1\7\62\0\1\3"+
    "\61\0\1\4\63\0\1\41\10\0\1\42\43\0\1\7"+
    "\3\0\5\7\1\0\5\7\14\0\23\7\1\0\1\7"+
    "\20\0\1\10\61\0\1\43\1\0\1\44\57\0\1\45"+
    "\61\0\1\46\60\0\1\47\60\0\1\50\60\0\1\51"+
    "\67\0\1\52\61\0\1\53\26\0\1\7\3\0\5\7"+
    "\1\0\5\7\14\0\1\7\1\54\1\7\1\55\17\7"+
    "\1\0\1\7\1\0\1\7\3\0\5\7\1\0\5\7"+
    "\14\0\14\7\1\56\6\7\1\0\1\7\1\0\1\7"+
    "\3\0\5\7\1\0\5\7\14\0\4\7\1\57\1\60"+
    "\1\61\14\7\1\0\1\7\1\0\1\7\3\0\5\7"+
    "\1\0\5\7\14\0\5\7\1\62\6\7\1\63\6\7"+
    "\1\0\1\7\1\0\1\7\3\0\5\7\1\0\5\7"+
    "\14\0\5\7\1\64\15\7\1\0\1\7\1\0\1\7"+
    "\3\0\5\7\1\0\5\7\14\0\5\7\1\65\15\7"+
    "\1\0\1\7\1\0\1\7\3\0\5\7\1\0\5\7"+
    "\14\0\6\7\1\66\14\7\1\0\1\7\1\0\1\7"+
    "\3\0\5\7\1\0\5\7\14\0\14\7\1\67\1\7"+
    "\1\70\4\7\1\0\1\7\1\0\1\7\3\0\5\7"+
    "\1\0\5\7\14\0\15\7\1\71\5\7\1\0\1\7"+
    "\1\0\1\7\3\0\5\7\1\0\5\7\14\0\4\7"+
    "\1\72\16\7\1\0\1\7\1\0\1\7\3\0\5\7"+
    "\1\0\5\7\14\0\2\7\1\73\20\7\1\0\1\7"+
    "\1\0\1\7\3\0\5\7\1\0\5\7\14\0\5\7"+
    "\1\74\15\7\1\0\1\7\2\75\1\0\56\75\6\0"+
    "\1\76\65\0\1\77\46\0\1\7\3\0\5\7\1\0"+
    "\5\7\14\0\2\7\1\100\20\7\1\0\1\7\1\0"+
    "\1\7\3\0\5\7\1\0\5\7\14\0\20\7\1\101"+
    "\2\7\1\0\1\7\1\0\1\7\3\0\5\7\1\0"+
    "\5\7\14\0\5\7\1\102\15\7\1\0\1\7\1\0"+
    "\1\7\3\0\5\7\1\0\5\7\14\0\14\7\1\103"+
    "\6\7\1\0\1\7\1\0\1\7\3\0\5\7\1\0"+
    "\5\7\14\0\4\7\1\104\16\7\1\0\1\7\1\0"+
    "\1\7\3\0\5\7\1\0\5\7\14\0\5\7\1\105"+
    "\15\7\1\0\1\7\1\0\1\7\3\0\5\7\1\0"+
    "\5\7\14\0\15\7\1\106\5\7\1\0\1\7\1\0"+
    "\1\7\3\0\5\7\1\0\5\7\14\0\1\107\22\7"+
    "\1\0\1\7\1\0\1\7\3\0\5\7\1\0\5\7"+
    "\14\0\1\110\22\7\1\0\1\7\1\0\1\7\3\0"+
    "\5\7\1\0\5\7\14\0\1\111\22\7\1\0\1\7"+
    "\1\0\1\7\3\0\5\7\1\0\5\7\14\0\1\112"+
    "\22\7\1\0\1\7\1\0\1\7\3\0\5\7\1\0"+
    "\5\7\14\0\6\7\1\113\14\7\1\0\1\7\1\0"+
    "\1\7\3\0\5\7\1\0\5\7\14\0\17\7\1\114"+
    "\3\7\1\0\1\7\1\0\1\7\3\0\5\7\1\0"+
    "\5\7\14\0\14\7\1\115\6\7\1\0\1\7\1\0"+
    "\1\7\3\0\5\7\1\0\5\7\14\0\1\7\1\116"+
    "\21\7\1\0\1\7\2\75\1\0\54\75\1\117\1\75"+
    "\7\0\1\120\70\0\1\121\42\0\1\7\3\0\5\7"+
    "\1\0\5\7\14\0\15\7\1\122\5\7\1\0\1\7"+
    "\1\0\1\7\3\0\5\7\1\0\5\7\14\0\6\7"+
    "\1\123\14\7\1\0\1\7\1\0\1\7\3\0\5\7"+
    "\1\0\5\7\14\0\17\7\1\124\3\7\1\0\1\7"+
    "\1\0\1\7\3\0\5\7\1\0\5\7\14\0\4\7"+
    "\1\125\16\7\1\0\1\7\1\0\1\7\3\0\5\7"+
    "\1\0\5\7\14\0\6\7\1\126\14\7\1\0\1\7"+
    "\1\0\1\7\3\0\5\7\1\0\5\7\14\0\11\7"+
    "\1\127\11\7\1\0\1\7\1\0\1\7\3\0\5\7"+
    "\1\0\5\7\14\0\1\7\1\130\21\7\1\0\1\7"+
    "\1\0\1\7\3\0\5\7\1\0\5\7\14\0\2\7"+
    "\1\131\20\7\1\0\1\7\1\0\1\7\3\0\5\7"+
    "\1\0\5\7\14\0\4\7\1\132\16\7\1\0\1\7"+
    "\1\0\1\7\3\0\5\7\1\0\5\7\14\0\11\7"+
    "\1\133\11\7\1\0\1\7\1\0\1\7\3\0\5\7"+
    "\1\0\5\7\14\0\15\7\1\134\5\7\1\0\1\7"+
    "\1\0\1\7\3\0\5\7\1\0\5\7\14\0\20\7"+
    "\1\135\2\7\1\0\1\7\1\0\1\7\3\0\5\7"+
    "\1\0\5\7\14\0\2\7\1\136\20\7\1\0\1\7"+
    "\10\0\1\137\55\0\1\140\54\0\1\7\3\0\5\7"+
    "\1\0\5\7\14\0\2\7\1\141\20\7\1\0\1\7"+
    "\1\0\1\7\3\0\5\7\1\0\5\7\14\0\15\7"+
    "\1\142\5\7\1\0\1\7\1\0\1\7\3\0\5\7"+
    "\1\0\5\7\14\0\21\7\1\143\1\7\1\0\1\7"+
    "\1\0\1\7\3\0\5\7\1\0\5\7\14\0\15\7"+
    "\1\144\5\7\1\0\1\7\1\0\1\7\3\0\5\7"+
    "\1\0\5\7\14\0\15\7\1\145\5\7\1\0\1\7"+
    "\1\0\1\7\3\0\5\7\1\0\5\7\14\0\22\7"+
    "\1\146\1\0\1\7\1\0\1\7\3\0\5\7\1\0"+
    "\5\7\14\0\1\147\22\7\1\0\1\7\11\0\1\150"+
    "\55\0\1\151\53\0\1\7\3\0\5\7\1\0\5\7"+
    "\14\0\2\7\1\152\20\7\1\0\1\7\1\0\1\7"+
    "\3\0\5\7\1\0\5\7\14\0\1\7\1\153\21\7"+
    "\1\0\1\7\12\0\1\154\55\0\1\155\52\0\1\7"+
    "\3\0\5\7\1\0\5\7\14\0\20\7\1\156\2\7"+
    "\1\0\1\7\13\0\1\157\57\0\1\160\47\0\1\7"+
    "\3\0\5\7\1\0\5\7\14\0\15\7\1\161\5\7"+
    "\1\0\1\7\14\0\1\162\1\163\50\0\1\164\70\0"+
    "\1\165\62\0\1\166\41\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4116];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\7\1\3\11\22\1\2\0"+
    "\11\11\21\1\3\0\20\1\2\0\15\1\2\0\7\1"+
    "\2\0\2\1\2\0\1\1\2\0\1\1\1\11\2\0"+
    "\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  private Parser yyparser;

  public Yylex(java.io.Reader r, Parser yyparser) {
    this(r);
    this.yyparser = yyparser;
    yyline = 1;
  }


  public int getLine() {
      return yyline;
  }



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 156) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 23: 
          { return Parser.TRUE;
          }
        case 39: break;
        case 4: 
          { yyparser.yylval = new ParserVal(yytext());
            return Parser.ID;
          }
        case 40: break;
        case 19: 
          { return Parser.DO;
          }
        case 41: break;
        case 29: 
          { return Parser.FLOAT;
          }
        case 42: break;
        case 16: 
          { return Parser.AND;
          }
        case 43: break;
        case 33: 
          { return Parser.WHILE;
          }
        case 44: break;
        case 20: 
          { return Parser.INT;
          }
        case 45: break;
        case 24: 
          { return Parser.BOOL;
          }
        case 46: break;
        case 6: 
          { return (int) yycharat(0);
          }
        case 47: break;
        case 36: 
          { yyparser.setDebug(true);
          }
        case 48: break;
        case 31: 
          { return Parser.BREAK;
          }
        case 49: break;
        case 34: 
          { return Parser.STRUCT;
          }
        case 50: break;
        case 15: 
          { return Parser.NEQ;
          }
        case 51: break;
        case 3: 
          { yyline++;
          }
        case 52: break;
        case 12: 
          { return Parser.EQ;
          }
        case 53: break;
        case 13: 
          { return Parser.GEQ;
          }
        case 54: break;
        case 1: 
          { System.err.println("Error: unexpected character '"+yytext()+"'"); return -1;
          }
        case 55: break;
        case 14: 
          { return Parser.LEQ;
          }
        case 56: break;
        case 8: 
          { return Parser.DOIS_PONTOS;
          }
        case 57: break;
        case 18: 
          { return Parser.IF;
          }
        case 58: break;
        case 32: 
          { return Parser.WRITE;
          }
        case 59: break;
        case 26: 
          { return Parser.MAIN;
          }
        case 60: break;
        case 21: 
          { return Parser.FOR;
          }
        case 61: break;
        case 35: 
          { return Parser.CONTINUE;
          }
        case 62: break;
        case 37: 
          { yyparser.setDebug(false);
          }
        case 63: break;
        case 22: 
          { yyparser.yylval = new ParserVal(yytext().substring(1, yylength() -1));
	     return Parser.LIT;
          }
        case 64: break;
        case 7: 
          { return Parser.INTERROGACAO;
          }
        case 65: break;
        case 30: 
          { return Parser.FALSE;
          }
        case 66: break;
        case 11: 
          { return Parser.DEC;
          }
        case 67: break;
        case 2: 
          { yyparser.yylval = new ParserVal(yytext()); 
         return Parser.NUM;
          }
        case 68: break;
        case 9: 
          { return Parser.INC;
          }
        case 69: break;
        case 38: 
          { yyparser.listarTS();
          }
        case 70: break;
        case 17: 
          { return Parser.OR;
          }
        case 71: break;
        case 10: 
          { return Parser.MAIS_IGUAL;
          }
        case 72: break;
        case 27: 
          { return Parser.READ;
          }
        case 73: break;
        case 28: 
          { return Parser.ELSE;
          }
        case 74: break;
        case 25: 
          { return Parser.VOID;
          }
        case 75: break;
        case 5: 
          { 
          }
        case 76: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return 0; }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
